### ISSUE TITLE
Thx for the EFI. It helped me fix some issues on my hack.

### ISSUE THREAD

**Issue by Overc1ocker** [Hlynford/Lenovo-ThinkStation-P310-Hackintosh#1]
In return, I'll share what i've learned.

CFG lock can be disabled using RU.efi and setting CFG-LOCK (0x197) to 0
You can remove the stolen mem patches using the hidden DVMT prealloc option. This will improve GPU performance and allow you to remove the stolenmem patches.

Set DVMT Pre-Allocated (0x520) to 0x2 (64mb pre-allocated memory)

**Comment by Hlynford** [comment]
Thanks, I will take your suggestion
